{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sberpi.serviceAccountName" . }}
  labels:
    {{- include "sberpi.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
